// Tech Knowledge Log - Interactive Features
// Smooth, modern interactions for the blog

(function() {
  'use strict';

  // Intersection Observer for fade-in animations
  const observerOptions = {
    threshold: 0.1,
    rootMargin: '0px 0px -50px 0px'
  };

  const fadeInObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        fadeInObserver.unobserve(entry.target);
      }
    });
  }, observerOptions);

  // Observe all fade-in elements
  document.addEventListener('DOMContentLoaded', () => {
    const fadeElements = document.querySelectorAll('.fade-in, .fade-in-up');
    fadeElements.forEach(el => fadeInObserver.observe(el));

    initializeSearch();
    initializeSmoothScroll();
    initializeHeaderScroll();
  });

  // Archive search functionality
  function initializeSearch() {
    const searchInput = document.getElementById('searchInput');
    if (!searchInput) return;

    const archiveList = document.getElementById('archiveList');
    const noResults = document.getElementById('noResults');
    const archiveItems = archiveList ? archiveList.querySelectorAll('.archive-item') : [];

    searchInput.addEventListener('input', debounce(function(e) {
      const searchTerm = e.target.value.toLowerCase().trim();
      let visibleCount = 0;

      archiveItems.forEach(item => {
        const title = item.dataset.title || '';
        const date = item.dataset.date || '';
        const matchesSearch = title.includes(searchTerm) || date.includes(searchTerm);

        if (matchesSearch) {
          item.style.display = '';
          visibleCount++;
          // Highlight matching text
          highlightText(item, searchTerm);
        } else {
          item.style.display = 'none';
        }
      });

      // Show/hide no results message
      if (noResults) {
        noResults.style.display = visibleCount === 0 ? 'block' : 'none';
      }
    }, 300));
  }

  // Highlight search matches
  function highlightText(element, searchTerm) {
    if (!searchTerm) {
      // Remove existing highlights
      const highlighted = element.querySelectorAll('.highlight');
      highlighted.forEach(span => {
        span.outerHTML = span.innerHTML;
      });
      return;
    }

    const link = element.querySelector('.archive-link');
    if (!link) return;

    const text = link.textContent;
    const regex = new RegExp(`(${escapeRegex(searchTerm)})`, 'gi');
    const highlightedText = text.replace(regex, '<span class="highlight">$1</span>');

    if (highlightedText !== text) {
      link.innerHTML = highlightedText;
    }
  }

  // Smooth scroll for anchor links
  function initializeSmoothScroll() {
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function(e) {
        const targetId = this.getAttribute('href');
        if (targetId === '#') return;

        const target = document.querySelector(targetId);
        if (target) {
          e.preventDefault();
          target.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          });
        }
      });
    });
  }

  // Header scroll effect
  function initializeHeaderScroll() {
    const header = document.querySelector('.site-header');
    if (!header) return;

    let lastScroll = 0;
    const scrollThreshold = 100;

    window.addEventListener('scroll', throttle(() => {
      const currentScroll = window.pageYOffset;

      if (currentScroll > scrollThreshold) {
        header.classList.add('scrolled');
      } else {
        header.classList.remove('scrolled');
      }

      lastScroll = currentScroll;
    }, 100));
  }

  // Utility: Debounce function
  function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
      const later = () => {
        clearTimeout(timeout);
        func(...args);
      };
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
    };
  }

  // Utility: Throttle function
  function throttle(func, limit) {
    let inThrottle;
    return function(...args) {
      if (!inThrottle) {
        func.apply(this, args);
        inThrottle = true;
        setTimeout(() => inThrottle = false, limit);
      }
    };
  }

  // Utility: Escape regex special characters
  function escapeRegex(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  // Add loading state removal
  window.addEventListener('load', () => {
    document.body.classList.add('loaded');
  });

})();

// ====== Posts index loader & renderer ======
// Fetch posts index generated by Jekyll
async function loadPostsIndex() {
  try {
    const res = await fetch('/tech-knowledge-log/assets/posts.json', { cache: 'no-store' });
    if (!res.ok) throw new Error('Failed to fetch posts.json');
    const data = await res.json();
    // merge and sort by date desc
    const all = [...(data.fundamentals || []), ...(data.papers || [])]
      .filter(p => p.title && p.url)
      .sort((a,b) => (a.date < b.date ? 1 : -1));
    return { all, fundamentals: data.fundamentals || [], papers: data.papers || [] };
  } catch (e) {
    console.error(e);
    return { all: [], fundamentals: [], papers: [] };
  }
}

// Render latest posts on index.html
function renderLatestPosts(list, posts, limit = 6) {
  if (!list) return;
  list.innerHTML = posts.slice(0, limit).map(p => (
    `<li class="post-item fade-in" data-title="${escapeHtml(p.title)}" data-date="${p.date}">
       <a class="post-link" href="${p.url}">${escapeHtml(p.title)}</a>
       <span class="post-meta">${p.date} · ${p.collection}</span>
     </li>`
  )).join('');
}

// Render archive page
function renderArchive(list, counter, posts) {
  if (!list) return;
  list.innerHTML = posts.map(p => (
    `<li class="archive-item fade-in" data-title="${escapeHtml(p.title)}" data-date="${p.date}">
       <a class="archive-link" href="${p.url}">${escapeHtml(p.title)}</a>
       <span class="archive-meta">${p.date} · ${p.collection}</span>
     </li>`
  )).join('');
  if (counter) counter.textContent = `${posts.length} posts`;
}

// Escape HTML utility (reuse regex escape above idea)
function escapeHtml(s) {
  return (s || '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
}

// Boot loader on DOMContentLoaded
document.addEventListener('DOMContentLoaded', async () => {
  const { all } = await loadPostsIndex();

  // index.html
  const postList = document.getElementById('postList');
  renderLatestPosts(postList, all, 6);

  // archive.html
  const archiveList = document.getElementById('archiveList');
  const archiveCount = document.getElementById('archiveCount');
  renderArchive(archiveList, archiveCount, all);

  // 활성화된 fade-in 옵저버가 있다면 새로 추가된 요소도 관찰
  try {
    const fadeElements = document.querySelectorAll('.fade-in, .fade-in-up');
    fadeElements.forEach(el => {
      if (typeof fadeInObserver !== 'undefined') fadeInObserver.observe(el);
    });
  } catch (_) {}
});
